### ISSUE TITLE
Item names not showing up in the Ordering Tablet item

### ISSUE THREAD

**Issue by MCAlexisYT** [Delta2Force/MCVmComputers#164] opened 2021-02-08 23:24 UTC
![MC VM Issue](https://user-images.githubusercontent.com/78766083/107293848-587a7580-6a3a-11eb-9cd8-1444bad838f2.PNG)
I can't get any item names as you can see in that image, and it's sort of like a guessing game when it comes to choosing the items (in that in-game "ordering tablet" thing of course), and because of the new items, I ended up choosing the wrong parts cuz I watched a video that seems to be older than the new update itself (at the time of posting this of course, on February 8th, 2021).

**Comment by MCAlexisYT** [comment] 2021-02-08 23:28
Might be because of the Fabric loader being corrupted (being replaced with all binary 0's, but the file was still there on the "master file table" so to speak) and giving me an error, then I deleted that Fabric Loader .jar file. Everything works just fine except that issue above.

**Comment by MCAlexisYT** [comment] 2021-02-14 23:55
Still waiting for help on how to fix this without having to _downgrade_ to Minecraft 1.15.2.

**Comment by coolthanhtube** [comment] 2021-02-15 11:17
I have the same issue. I don't really know what happened to the Fabric or the mod. It got me crazy to guess all the items.

**Comment by MCAlexisYT** [comment] 2021-02-15 14:36
@coolthanhtube But at least, you can "cheat" by just grabbing the items off of the creative menu.
¯\_(ツ)_/¯

**Comment by coolthanhtube** [comment] 2021-02-17 12:17
Well, that's only in creative mode, so if you're in survival mode?

**Comment by CoccodrillooXDS** [comment] 2021-02-26 17:13
Duplicate of #156
Consider commenting on that issue.

**Closed by CoccodrillooXDS** 2021-02-26 17:13 UTC
Labels: bug

**Comment by y2k04** [comment] 2023-03-26 02:48
Duplicate of #127
