### ISSUE TITLE
Forge/vivecraft?

### ISSUE THREAD

**Issue by Liquidcooled** [Delta2Force/MCVmComputers#159] opened 2021-02-02 16:24 UTC
Im wondering if it's possible that you could port this to forge for the sole reason of using it with vivecraft. I know porting to forge isn't easy so I'd be willing to donate to make it happen because this would be so cool to use in VR.

**Comment by lc67846** [comment] 2021-02-03 03:44
Good Idea That Will Be Cool And You Can Tap On the keyboard and it sends a
sIgnal and same with the mouse but you move it around and left click the
left trriger and right click is right Trriger

**Comment by pivinx1** [comment] 2021-03-25 08:22
Forge has an different codebase, thus an port to Forge probably can take AGES, in the VM you would need to have some sort of an screen keyboard since it requires to have an keyboard input from host to type inside, also without a keyboard you would be unable to "get out" of the input capture of an VM as it uses an keybind to disable capturing input from the host and forwarding it to the VM. Mouse input with Vivecraft might be possible though.

**Comment by y2k04** [comment] 2023-03-26 02:47
Duplicate of #57

**Closed by y2k04** 2023-03-26 02:47 UTC
Labels: enhancement
