### ISSUE TITLE
monitors not showing anything.

### ISSUE THREAD

**Issue by BlueFurr** [Delta2Force/MCVmComputers#70] opened 2020-08-26 23:39 UTC
I'm having a problem where i will have an ISO and all the computer parts installed and i'll turn on the pc but none of the monitors will show anything

**Comment by CoccodrillooXDS** [comment] 2020-08-28 10:12
Does the VM start? (Check in VirtualBox)

**Comment by y2k04** [comment] 2023-03-26 03:38
Duplicate of #45

**Closed by y2k04** 2023-03-26 03:38 UTC
Labels: bug
