### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by goosetalk** [Delta2Force/MCVmComputers#258] opened 2022-05-07 02:01 UTC
Can you publish VMWare Edition?I don't like VirtualBox,it's not good for me

**Comment by Maxey1950** [comment] 2022-06-12 19:06
Yea I really want one for vmware workstaion pro @everyone @Owener

**Comment by Meister1593** [comment] 2022-06-17 20:32
there was an attempt on doing qemu, but it was stalled
Overall project is a bit stalled and required major refactor

**Comment by goosetalk** [comment] 2022-06-19 02:29
> 曾尝试做 qemu，但停滞不前 整体项目有点停滞，需要重大重构

I think the compatibility is not good

**Comment by goosetalk** [comment] 2022-06-19 02:39
Also, what is the working principle of the module? Can you send a docx that works

**Comment by goosetalk** [comment] 2022-06-19 02:40
Can I participate in development

**Comment by Meister1593** [comment] 2022-06-19 05:20
> Can I participate in development

You can send pull requests and they probably will be reviewed, especially considering that commits were made very recently.
As for documentatiom - there is none for the code as far as I am aware. This mod needs very heavy refactor in area of managing inputs on screen, passing byteimage to other players and so on.
I personally wanted to make some progress, but was busy at my university. Next week I might try an attempt on starting refactor/rewrite. I will let you know when that happens. There is a hope and some ideas on how this can be improved.

**Comment by Delta2Force** [comment] 2022-06-19 09:31
> > Can I participate in development
> 
> You can send pull requests and they probably will be reviewed, especially considering that commits were made very recently. As for documentatiom - there is none for the code as far as I am aware. This mod needs very heavy refactor in area of managing inputs on screen, passing byteimage to other players and so on. I personally wanted to make some progress, but was busy at my university. Next week I might try an attempt on starting refactor/rewrite. I will let you know when that happens. There is a hope and some ideas on how this can be improved.

I myself have a very large break coming up soon and thought about just creating a new repo and starting from scratch, making it more modular and paying more attention to actually writing good code. Back when I wrote this it was basically just for a cool gif so I wrote awful code. Also I consistently committed code that wouldn't compile to master even though I wanted to structure it as an open source project. If you want, we can get in touch and work on it together, maybe even make something outside of the gimmick that it currently is (tech mod?)

**Comment by Meister1593** [comment] 2022-06-19 15:29
> > > Can I participate in development
> > 
> > 
> > You can send pull requests and they probably will be reviewed, especially considering that commits were made very recently. As for documentatiom - there is none for the code as far as I am aware. This mod needs very heavy refactor in area of managing inputs on screen, passing byteimage to other players and so on. I personally wanted to make some progress, but was busy at my university. Next week I might try an attempt on starting refactor/rewrite. I will let you know when that happens. There is a hope and some ideas on how this can be improved.
> 
> I myself have a very large break coming up soon and thought about just creating a new repo and starting from scratch, making it more modular and paying more attention to actually writing good code. Back when I wrote this it was basically just for a cool gif so I wrote awful code. Also I consistently committed code that wouldn't compile to master even though I wanted to structure it as an open source project. If you want, we can get in touch and work on it together, maybe even make something outside of the gimmick that it currently is (tech mod?)

i'm all for it, sure

**Comment by KingTino104** [comment] 2022-07-09 09:46
> 

Agree, you should start from scratch, this hasn't received updates, and it's better to start from scratch because nobody will use this if you update it.

**Comment by goosetalk** [comment] 2022-09-25 11:13
ok

**Comment by y2k04** [comment] 2022-12-04 23:18
@goosetalk I am updating it to 1.19.2 right now. The code does require some work (replacing obsolete and deprecated methods and classes), but so far it is going well with going through each class one by one to fix the errors. I also made it grab the latest VirtualBox SDK and moving vboxjws.jar to the lib folder. So with that it now supports VirtualBox 7.0.4.

**Comment by poopdog000** [comment] 2023-02-03 20:28
> @goosetalk I am updating it to 1.19.2 right now. The code does require some work (replacing obsolete and deprecated methods and classes), but so far it is going well with going through each class one by one to fix the errors. I also made it grab the latest VirtualBox SDK and moving vboxjws.jar to the lib folder. So with that it now supports VirtualBox 7.0.4.

make it work it don't work with VMware

**Comment by poopdog000** [comment] 2023-02-03 20:30
> @goosetalk I am updating it to 1.19.2 right now. The code does require some work (replacing obsolete and deprecated methods and classes), but so far it is going well with going through each class one by one to fix the errors. I also made it grab the latest VirtualBox SDK and moving vboxjws.jar to the lib folder. So with that it now supports VirtualBox 7.0.4.

make it work with VMware

**Comment by y2k04** [comment] 2023-02-04 03:13
That is being researched currently, but there is not much documentation that is useful. We are better off investing time in QEMU development instead of VMware unfortunately.

**Comment by y2k04** [comment] 2023-03-25 21:21
Closing issue due to it not being able to be implemented. (I'm sad too)

**Closed by y2k04** 2023-03-25 21:21 UTC

**Comment by goosetalk** [comment] 2023-03-26 03:04
Sorry, I've been a bit busy lately and can't reply

**Comment by y2k04** [comment] 2023-03-26 03:22
Don't worry :)

**Comment by y2k04** [comment] 2023-03-26 03:39
Duplicate of #80
