### ISSUE TITLE
Windows 10 hanging at boot

### ISSUE THREAD

**Issue by MaybeCooper2** [Delta2Force/MCVmComputers#195] opened 2021-04-11 22:09 UTC
I have no idea if this is because of a setting that the mod sets, but whenever I use this mod to boot a Windows 10 image (downloaded from the official Microsoft website). I gave the VM 8 GB ram, 1/2 CPU, 64-bit motherboard, GPU. Also, when I boot the SAME image on a regular VM outside of the mod, it boots to setup immediately. Does anyone know what is happening? 

Also: Windows 95 and Windows XP booted fine in the mod. When I tried Windows 7 or higher, it wouldn't get past the official boot screen, it would just give me a hardware error.

I also attached a video of it.

https://user-images.githubusercontent.com/82343429/114322952-ffd66000-9af0-11eb-84e5-9d655590be32.mp4

**Comment by EAZYBLACK** [comment] 2021-12-01 19:54
Open ViurtalBox And Find VMComputers Viurtal Machine Edit the video controller from vmsvga to vboxvga to vboxsvga try all video controllers

**Comment by y2k04** [comment] 2023-03-26 03:16
Duplicate of #78

**Closed by y2k04** 2023-03-26 03:16 UTC
Labels: bug
