### ISSUE TITLE
The options in the tablet don't show up in the latest update.

### ISSUE THREAD

**Issue by Harry989** [Delta2Force/MCVmComputers#128] opened 2020-11-02 21:45 UTC
It still works, I just have no idea what I'm buying. I've attached a screenshot of the issue.
![image](https://user-images.githubusercontent.com/46330151/97922639-b4a36e80-1d54-11eb-8a62-fa13feeb8f93.png)

**Comment by Busaruba2011** [comment] 2020-11-15 13:04
If you're in creative mode, just get it from the inventory.

**Comment by moglol** [comment] 2021-01-25 13:41
> If you're in creative mode, just get it from the inventory.

the issue is it also happens in survival
![image](https://user-images.githubusercontent.com/70176674/105713390-03efda00-5f13-11eb-81b9-68cfb353faac.png)

**Comment by y2k04** [comment] 2023-03-26 02:49
Duplicate of #127

**Closed by y2k04** 2023-03-26 02:49 UTC
Labels: bug
