### ISSUE TITLE
Release 1.5

### ISSUE THREAD

**Issue by swordlink1** [Delta2Force/MCVmComputers#115] opened 2020-10-22 23:38 UTC
This probably isn't really a issue nor a enhancement for a existing version, but it would be nice to have a new version. Maybe add audio support or add ram sticks with less amount of ram? Maybe introduce new displays or add rgb stuff?

**Comment by swordlink1** [comment] 2020-10-22 23:42
I just realized that they added more ram sticks with less amount of ram, but what about the other stuff?

**Comment by Frede0021** [comment] 2020-10-26 16:11
I would like to see multi VM support and a way to connect a specific monitor to a specific computer. and maybe a USB flash drive to wich you can add an iso file much like you can add an image to a hard drive and you can transfer files between computers/VMs. maybe being a bit more optimised on input lag that doesnt exist in VirtualBox. maybe floppy disks. I'd also cange the CPUs to a core count if it is possible. just some stuff I would add to your list and I can see a good future for this mod if development is going to continue. honestly in my view it is one of the best mods for MC at least it will be if development is gonna continue

**Comment by Frede0021** [comment] 2020-10-26 16:14
and for servers a way to lock images/VMs/monitors and PCs for players who are not OP on the server

**Comment by y2k04** [comment] 2022-12-04 05:09
> This probably isn't really a issue nor a enhancement for a existing version, but it would be nice to have a new version. Maybe add audio support or add ram sticks with less amount of ram? Maybe introduce new displays or add rgb stuff?

I will definitely look into it (I am taking over development).

**Comment by y2k04** [comment] 2023-03-26 03:14
Duplicate of #108

**Closed by y2k04** 2023-03-26 03:14 UTC
Labels: enhancement
