### ISSUE TITLE
Forge 

### ISSUE THREAD

**Issue by Cielse** [Delta2Force/MCVmComputers#266] opened 2022-10-06 15:14 UTC
forge pls

**Comment by Natemo6348** [comment] 2022-11-07 01:02
I would also like a Forge version, but if it's possible, I have no idea. Also would like to know if I could eventually be able to use virtualbox 7 with this mod.

**Comment by y2k04** [comment] 2023-03-25 21:26
@Cielse That is on the todo now. Thanks!

@Natemo6348 #280

**Comment by y2k04** [comment] 2023-03-25 21:41
Duplicate of #249

**Closed by y2k04** 2023-03-25 21:41 UTC
Labels: duplicate, enhancement
