### ISSUE TITLE
mouse cursor not showing up

### ISSUE THREAD

**Issue by CBPolarBear** [Delta2Force/MCVmComputers#135] opened 2020-11-14 15:08 UTC
when in focus, the mouse cursor still functions, however it does not show on the screen.

**Comment by Busaruba2011** [comment] 2020-11-15 08:07
What OS is the guest and host? If the guest is Ubuntu, the mouse doesn't show up for anyone for some reason.

**Comment by CBPolarBear** [comment] 2020-11-16 13:53
yes, im running the mod on windows 10, and the mod is running a distro of
ubuntu called linux mint.

**Comment by Delta2Force** [comment] 2020-11-16 15:29
Yeah, that's a common issue with Linux OSs, don't really know why that happens

**Comment by Busaruba2011** [comment] 2020-11-16 17:23
@Delta2Force I'll try with Ubuntu 20.10 and see if it works and get back to you.

**Comment by patcon** [comment] 2020-12-07 23:36
@Busaruba2011 any update? Thanks :)

**Comment by y2k04** [comment] 2023-03-26 03:13
Duplicate of #14

**Closed by y2k04** 2023-03-26 03:13 UTC
Labels: bug
