### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CatProgrammer-Java** [Delta2Force/MCVmComputers#210] opened 2021-06-25 17:33 UTC
Game hanging on "All values valid. Attempting to start VirtualBox."

**Comment by Delta2Force** [comment] 2021-07-04 13:36
Can you upload your log (`.minecraft/logs/latest.log`) to a website like pastebin or something like that after this occurs?

**Comment by ModDownloader** [comment] 2021-07-08 07:06
> Can you upload your log (`.minecraft/logs/latest.log`) to a website like pastebin or something like that after this occurs?

I send it on next week, please do not close

**Comment by ModDownloader** [comment] 2021-07-13 14:56
https://pastebin.com/H8yKhsUS

**Comment by Delta2Force** [comment] 2021-07-15 20:46
Which version of Java are you running? In Java 8 this shouldn't be a problem

**Comment by ModDownloader** [comment] 2021-07-16 16:44
16

**Comment by Delta2Force** [comment] 2021-07-23 00:36
When the mod version for Minecraft 1.17 comes out this bug will be fixed

**Comment by y2k04** [comment] 2023-03-26 03:35
Duplicate of #197

**Closed by y2k04** 2023-03-26 03:35 UTC
Labels: bug
