### ISSUE TITLE
cursor does not appear

### ISSUE THREAD

**Issue by BmoreKarl** [Delta2Force/MCVmComputers#172] opened 2021-03-02 19:20 UTC
i am running ubuntu on the vm, i cannot see any cursor but it affects things on screen when i click. can i fix this by customizing my cursor?

**Comment by Busaruba2011** [comment] 2021-03-02 19:21
This is a problem with Linux guests in general.

**Comment by BmoreKarl** [comment] 2021-03-02 19:32
do you know of any solution?

**Comment by Busaruba2011** [comment] 2021-03-09 17:18
There isn't one

**Comment by BmoreKarl** [comment] 2021-03-10 14:08
ok

**Comment by y2k04** [comment] 2023-03-26 03:13
Duplicate of #14

**Closed by y2k04** 2023-03-26 03:13 UTC
Labels: bug
