### ISSUE TITLE
Using the default path instead of the input resulting in error when starting the mod for the first time "Unable to start VirtualBox" VirtualBox (6.1.22)

### ISSUE THREAD

**Issue by moddingforreal** [Delta2Force/MCVmComputers#243] opened 2022-01-22 18:01 UTC
# "Can't start VirtualBox" but VirtualBox up-to-date

VirtualBox is up-to-date but the mod doesn't seem to be able to start it. It gives back this error in the latest.log:
```
[18:49:00] [main/INFO]: [STDERR]: java.io.IOException: Cannot run program "C:\Program Files\Oracle\VirtualBox\vboxmanage.exe": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
```
Translating to:
```
[18:49:00] [main/INFO]: [STDERR]: java.io.IOException: Cannot run program "C:\Program Files\Oracle\VirtualBox\vboxmanage.exe": CreateProcess error=2, The System cannot find the specified File
```

This implies that the mod completely ignores the path I _actually_ put in (D:\VirtualBox).
Please fix this by making it take the actual path. This issue may also occur with the folder for ISOs and VHDs, so please also take what the user actually inputs.

**Comment by y2k04** [comment] 2023-03-25 21:46
Yeah I had that problem as well. I will work on a fix for it soon.

**Comment by y2k04** [comment] 2023-03-26 03:29
Duplicate of #5

**Closed by y2k04** 2023-03-26 03:29 UTC
Labels: bug
