### ISSUE TITLE
Is it possible to make it compatible with VMware?

### ISSUE THREAD

**Issue by 4beep** [Delta2Force/MCVmComputers#251] opened 2022-02-09 05:05 UTC

**Comment by 4winyt** [comment] 2022-04-01 18:27
I mean, most of the code would have to be rewritten.

**Comment by 4beep** [comment] 2022-04-07 02:50
> I mean, most of the code would have to be rewritten.

Yes, But atleast the virtualization would be WAY MORE FASTER

**Comment by y2k04** [comment] 2022-10-22 02:43
I would have to look, but I am pretty sure there is a headless mode for VMware. Otherwise, the next best option is QEMU

**Comment by 4beep** [comment] 2022-10-28 23:42
If theres how, please make aw tutorial on how to make it!

**Comment by y2k04** [comment] 2023-03-25 21:38
After further reading on APIs and possible solutions, VMware will not be supported due to the lack of interaction it can have.

**Comment by y2k04** [comment] 2023-03-25 21:39
Also, duplicate of #258

**Closed by y2k04** 2023-03-25 21:38 UTC
