### ISSUE TITLE
vboxwebsrv is still running error

### ISSUE THREAD

**Issue by Tonkyboi1** [Delta2Force/MCVmComputers#218] opened 2021-07-20 00:23 UTC
So... It says vboxwebsrv is still running but it isn't. Look at the images
![1-help](https://user-images.githubusercontent.com/87203360/126243728-80b2744f-b3d8-407d-81a3-7689b70d58dd.png)
and this:
![EE](https://user-images.githubusercontent.com/87203360/126243799-23f21864-9a41-4402-984d-dd3b5b34f79b.png)
(Also the log):
[2021-07-19-1.log](https://github.com/Delta2Force/MCVmComputers/files/6844574/2021-07-19-1.log)

**Comment by Delta2Force** [comment] 2021-07-23 00:34
It's saying `C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe`, you probably specified a wrong path? Which version of VirtualBox did you try to pass to the mod?

**Comment by Tonkyboi1** [comment] 2021-07-29 22:01
> It's saying `C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe`, you probably specified a wrong path? Which version of VirtualBox did you try to pass to the mod?

6.1 (also sry for the late reply my pc was broken for a while)

**Comment by MegaSa1nt** [comment] 2021-08-13 07:11
try downloading 6.1.26 without editing path to install

**Comment by 581121** [comment] 2022-03-19 16:27
i am getting the same error and before you say put C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe I already tried it but its says directory doesn't exist and vm version is 6.1.32 or something

**Comment by 581121** [comment] 2022-03-20 09:37
please respond fast

**Comment by Dragonlord1005** [comment] 2022-03-25 03:31
virtualbox renamed it to VBoxWebSrv or something like that, he needs to fix it @581121

**Comment by philix1** [comment] 2022-04-06 22:57
i have problem to

**Comment by y2k04** [comment] 2023-03-26 03:35
Duplicate of #197

**Closed by y2k04** 2023-03-26 03:35 UTC
Labels: bug, duplicate
