### ISSUE TITLE
Cursor not showing

### ISSUE THREAD

**Issue by EG2603** [Delta2Force/MCVmComputers#257] opened 2022-04-26 16:02 UTC
I installed ubuntu but the cursor isn't visible

**Comment by Vichingo455** [comment] 2022-08-30 08:40
Same issue with Windows, sometimes the cursor is not visible

**Comment by y2k04** [comment] 2023-03-25 21:34
Could you please elaborate on this and attach a screenshot as well as the log file?

**Comment by y2k04** [comment] 2023-03-26 03:12
Duplicate of #14

**Closed by y2k04** 2023-03-26 03:12 UTC
Labels: bug
