### ISSUE TITLE
CPU Cores is only limited to single core

### ISSUE THREAD

**Issue by BiruLangit8176** [Delta2Force/MCVmComputers#259] opened 2022-05-13 02:15 UTC

**Comment by TCAtrevor** [comment] 2022-08-19 14:03
A fix for this was made, and even pulled, but never released in a version officially. I made a release of the version with functioning multi-core if you are interested.
https://github.com/TCAtrevor/MCVmComputers/releases/latest

**Comment by y2k04** [comment] 2023-03-25 21:30
We will officially support this soon. Now adding to to-do list.

**Comment by y2k04** [comment] 2023-03-26 03:11
Duplicate of #161

**Closed by y2k04** 2023-03-26 03:11 UTC
Labels: enhancement
