### ISSUE TITLE
Running a VM whilst being in a server [Bug]

### ISSUE THREAD

**Issue by BlueJay113** [Delta2Force/MCVmComputers#36] opened 2020-07-07 04:21 UTC
![Imgur](https://i.imgur.com/Pc1ur00.png)

I start the VM and then the server kicks me off the server because of this error.

**Comment by Delta2Force** [comment] 2020-07-07 18:06
What OS are you using? This might be caused by a too big resolution displayed on the screen...

**Comment by BlueJay113** [comment] 2020-07-07 22:10
> What OS are you using? This might be caused by a too big resolution displayed on the screen...

For the host I am using Windows 10, for the guest I was trying to run Windows 2000. And yes I had put the resolution up to 1024x768 instead of 800x600.

**Comment by BlueJay113** [comment] 2020-07-07 22:36
You could always try this bug out for yourself?
[mcpclab.skynode.host](mcpclab.skynode.host)

**Comment by lmore377** [comment] 2020-07-10 01:00
@Delta2Force what if you send video over a websocket or rtsp connection when the mod detects that it's on a server?

**Comment by BlueJay113** [comment] 2020-07-10 01:04
The server is booting up right now.

**Comment by BlueJay113** [comment] 2020-07-10 01:07
And also I might make a port of this mod so I could make it use QEMU instead (just for testing purposes). 256MB of VRAM is wayyyyyy too low.

**Comment by Delta2Force** [comment] 2020-07-10 06:44
> @Delta2Force what if you send video over a websocket or rtsp connection when the mod detects that it's on a server?

I thought about doing this, but opted for packets since it’s easier to implement

**Comment by Delta2Force** [comment] 2020-07-10 06:46
> And also I might make a port of this mod so I could make it use QEMU instead (just for testing purposes). 256MB of VRAM is wayyyyyy too low.

Yeah, QEMU is great. I made the mod with virtualbox since it has an easy API which works cross platform without any issues.

**Comment by BlueJay113** [comment] 2020-07-10 06:47
@Delta2Force Come on my server and see what I mean

**Comment by BlueJay113** [comment] 2020-07-10 06:49
(btw, the server is dedicated to this mod :D )

**Comment by BlueJay113** [comment] 2020-07-10 07:01
Crash log
[crash-2020-07-10_17.00.24-client.txt](https://github.com/Delta2Force/MCVmComputers/files/4901530/crash-2020-07-10_17.00.24-client.txt)

**Comment by BlueJay113** [comment] 2020-07-10 07:05
Server Error:
```
[06:55:00] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Duplicate id value for 7!
at net.minecraft.class_2945.method_12784(class_2945.java:80) ~[intermediary-server.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.method_5693(EntityFlatScreen.java:58) ~[mcvmcomputers-1.4.3.jar:?]
at net.minecraft.class_1297.<init>(class_1297.java:253) ~[intermediary-server.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.<init>(EntityFlatScreen.java:32) ~[mcvmcomputers-1.4.3.jar:?]
at mcvmcomputers.entities.EntityFlatScreen.<init>(EntityFlatScreen.java:41) ~[mcvmcomputers-1.4.3.jar:?]
at mcvmcomputers.item.ItemFlatScreen.method_7836(ItemFlatScreen.java:32) ~[mcvmcomputers-1.4.3.jar:?]
at net.minecraft.class_1799.method_7913(class_1799.java:206) ~[intermediary-server.jar:?]
at net.minecraft.class_3225.method_14256(class_3225.java:278) ~[intermediary-server.jar:?]
at net.minecraft.class_3244.method_12065(class_3244.java:966) ~[intermediary-server.jar:?]
at net.minecraft.class_2886.method_12550(class_2886.java:31) ~[intermediary-server.jar:?]
at net.minecraft.class_2886.method_11054(class_2886.java:9) ~[intermediary-server.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-server.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:743) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:138) [intermediary-server.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:725) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:719) [intermediary-server.jar:?]
at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:703) [intermediary-server.jar:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [intermediary-server.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Delta2Force** [comment] 2020-07-10 10:43
The server is down right now, right?

**Comment by BlueJay113** [comment] 2020-07-10 10:45
> The server is down right now, right?

Yes, give me a sec, turning it back on, it will be on for 2 hours

**Comment by BlueJay113** [comment] 2020-07-10 10:50
> The server is down right now, right?

Server is now booting, it will be a minute to turn on completely

**Comment by Delta2Force** [comment] 2020-07-10 11:07
Looks nice! Did you place the squashed CRT screens lol

**Comment by Delta2Force** [comment] 2020-07-10 11:34
Anyway, im working on fixing the bug

**Comment by BlueJay113** [comment] 2020-07-10 21:51
> Looks nice! Did you place the squashed CRT screens lol

Thanks 😁, I’ve been making that lobby for the last 3 days.

**Comment by Delta2Force** [comment] 2020-07-11 13:09
It should be fixed now :)

**Closed by Delta2Force** 2020-07-11 13:09 UTC
Labels: bug
