### ISSUE TITLE
Mod doesn't open vboxwebsrv

### ISSUE THREAD

**Issue by benjiae** [Delta2Force/MCVmComputers#203] opened 2021-05-10 18:16 UTC
Hi, VM Computers doesn't start virtualbox, i checked the logs and it said: "Cannot run program "C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe" " saying that the system could not find the file, the problem is. i sayed to the mod setup that i dont have virtualbox on the default directory, but still searches vboxwebsrv on the default directory

**Comment by y2k04** [comment] 2023-03-26 03:36
Duplicate of #197

**Closed by y2k04** 2023-03-26 03:36 UTC
Labels: bug, duplicate
