### ISSUE TITLE
VitrualBox Installation Direction on Mac OS

### ISSUE THREAD

**Issue by PhilipsGamer** [Delta2Force/MCVmComputers#264] opened 2022-09-09 11:39 UTC

**Comment by y2k04** [comment] 2023-01-03 23:12
[https://osxdaily.com/2021/07/15/how-install-macos-virtualbox-windows/](https://osxdaily.com/2021/07/15/how-install-macos-virtualbox-windows/)

**Comment by y2k04** [comment] 2023-03-26 03:26
Duplicate of #123

**Closed by y2k04** 2023-03-26 03:26 UTC
Labels: invalid
