### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by poopdog000** [Delta2Force/MCVmComputers#277] opened 2023-02-03 20:24 UTC
it don't work with VMware

**Comment by NixPlayer** [comment] 2023-03-10 18:23
vmware it's closed source, so delta2force can't develop with it, cuz he doesn't have the source code

**Comment by y2k04** [comment] 2023-03-22 03:04
We talked about it, but yeah after doing lots of research, it is not worth attempting to reverse engineer the dlls or any of the other library calls. Sure, it is able to be done, but that's a lot of time that could be spent developing it for QEMU instead.

**Comment by y2k04** [comment] 2023-03-22 05:34
Also a duplicate of #258

**Comment by y2k04** [comment] 2023-03-25 21:20
Closing issue due to it not being **able to be** implemented. (I'm sad too)

**Closed by y2k04** 2023-03-25 21:20 UTC

**Comment by y2k04** [comment] 2023-03-26 03:38
Duplicate of #80
