### ISSUE TITLE
Ubuntu won't do anything after boot

### ISSUE THREAD

**Issue by MariahJauregui** [Delta2Force/MCVmComputers#71] opened 2020-09-08 02:01 UTC
Setting up ubuntu was fine, except no mouse cursor, but after it's setup, it's just black. It shows the ubuntu loading screen and then nothing.

**Comment by Delta2Force** [comment] 2020-09-09 19:33
Huh. Do you see anything if you access the virtual machine directly through VirtualBox?

**Comment by MariahJauregui** [comment] 2020-09-09 19:36
Yes

**Comment by Delta2Force** [comment] 2020-09-09 19:38
So, you start the VM ingame -> the screen is black ingame -> you look at VirtualBox -> the screen is not black?

**Comment by MariahJauregui** [comment] 2020-09-09 19:40
Yup

**Comment by MariahJauregui** [comment] 2020-09-09 19:41
I'll have to check

**Comment by MariahJauregui** [comment] 2020-09-09 19:51
It is black

**Comment by MariahJauregui** [comment] 2020-09-09 19:55
It worked after I showed it in virtualbox and closed the virtualbox window

**Comment by MariahJauregui** [comment] 2020-09-09 19:57
There's no mouse cursor

**Comment by Delta2Force** [comment] 2020-09-10 10:48
Yeah the mouse cursor has been a problem for a while (#14)

**Comment by lc67846** [comment] 2020-11-21 05:44
It Only Works On Windows Linux Only Has Post Coding Powers Windows Has More Post Processing

**Comment by Half-Life-3** [comment] 2021-02-10 01:31
I had the same issue, but it appears to be a problem with VirtualBox rather than the mod... Ubuntu 20.04 will not boot in a headless VM when Guest Additions are installed. Uninstalling Guest Additions fixes the issue.

**Comment by y2k04** [comment] 2023-03-26 03:13
Duplicate of #14

**Closed by y2k04** 2023-03-26 03:13 UTC
Labels: bug
