### ISSUE TITLE
The Mod is Stuck at "Attempting to start VirtualBox" (Same name, different issue)

### ISSUE THREAD

**Issue by ZandercraftGames** [Delta2Force/MCVmComputers#233] opened 2021-11-09 07:43 UTC
**Issue**  
The game gets stuck on the "Attempting to start VirtualBox screen". This occurs after a re-installation of VirtualBox and a restart. I have tried with both VirtualBox and all its services killed as well as with the VirtualBox window open and running. Neither works.

**Console Errors**  
The following is the error that the program outputs. This is output once and then just sits with no changes.  
```
[02:31:52] [Thread-56/INFO]: [STDERR]: java.lang.NoClassDefFoundError: javax/xml/ws/Service
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at org.virtualbox_6_1.PortPool.getPort(PortPool.java:128)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at org.virtualbox_6_1.PortPool.preinit(PortPool.java:101)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at org.virtualbox_6_1.PortPool.access$200(PortPool.java:54)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at org.virtualbox_6_1.PortPool$1.run(PortPool.java:78)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:31:52] [Thread-56/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Service
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:31:52] [Thread-56/INFO]: [STDERR]: 	... 10 more
[02:31:52] [Thread-55/INFO]: [STDERR]: java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at org.virtualbox_6_1.VirtualBoxManager.<clinit>(VirtualBoxManager.java:527)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues$2.run(SetupPageMaxValues.java:143)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[02:31:52] [Thread-55/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: javax.xml.ws.WebServiceException
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[02:31:52] [Thread-55/INFO]: [STDERR]: 	... 3 more
```  

**Environment Information**  
Mod Version: 1.4.15  
Virtualbox Version: 6.1.28 r147628 (Qt5.6.2)  
Fabric Version: 0.11.7  
Minecraft Version: 1.16.5  
FabricAPI Version: 0.41.3+1.16  
Windows Version: 11 21H2 22000.282 + Windows Feature Experience Pack 1000.22000.318.0

**Comment by skyedoesgaming** [comment] 2021-11-13 13:47
Happening with me too, but im on windows 10.

**Comment by QEXLAUWASD** [comment] 2022-01-09 07:57
I using Java 8 to fix it

**Comment by ZandercraftGames** [comment] 2022-02-04 22:46
@QEXLAUWASD That did not fix it for me.

**Comment by OctonalXX** [comment] 2022-06-26 07:16
Happens with me too, when I reinstalled VirtualBox it worked once.

**Comment by y2k04** [comment] 2023-03-26 03:35
Duplicate of #197

**Closed by y2k04** 2023-03-26 03:35 UTC
Labels: bug
