### ISSUE TITLE
Mod Completely Ignores VBox Path

### ISSUE THREAD

**Issue by El-Virus** [Delta2Force/MCVmComputers#235] opened 2021-11-22 17:59 UTC
It seems the mod completely ignores the specified VBox Path.
For example, I have Virtual Box installed on my D drive, and I've set the path to it:
![imagen](https://user-images.githubusercontent.com/36414402/142908440-2e0c80a5-fb86-4720-abf3-e2f7fdc9cdbf.png)
But the log shows this:
`java.io.IOException: Cannot run program "C:\Program Files\Oracle\VirtualBox\vboxmanage.exe": CreateProcess error=2, Could not file the specified file`

**Comment by y2k04** [comment] 2023-03-26 03:30
Duplicate of #5

**Closed by y2k04** 2023-03-26 03:30 UTC
Labels: bug
