### ISSUE TITLE
keep getting an error even though all of my inputs are correct

### ISSUE THREAD

**Issue by Ncat19** [Delta2Force/MCVmComputers#244] opened 2022-01-22 22:09 UTC
![Screenshot from 2022-01-22 22-04-45](https://user-images.githubusercontent.com/81239150/150656943-3b49683a-7fbb-4ce7-831a-8edea561da68.png)

i consistently get this error even though i've set up everything correctly an all my input values are set to default. _s there something that i haven't done right?

**Comment by Ncat19** [comment] 2022-01-23 09:27
this is where i think the error was in the logs:
### 
**org.virtualbox_6_1.VirtualBoxManager.connect(VirtualBoxManager.java:566)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	... 2 more
[09:21:15] [Thread-8/INFO]: [STDERR]: Caused by: java.net.ConnectException: Connection refused (Connection refused)**

here are the full logs: 

[09:20:58] [main/INFO]: Loading Minecraft 1.15.2 with Fabric Loader 0.12.12
[09:20:58] [main/INFO]: Loading 43 mods:
	- fabric 0.28.5+1.15
	- fabric-api-base 0.1.2+9826cad80c via fabric
	- fabric-biomes-v1 0.1.6+c1455e800c via fabric
	- fabric-blockrenderlayer-v1 1.1.5+c1455e800c via fabric
	- fabric-climbable-api-v1 1.0.1+c1455e800c via fabric
	- fabric-command-api-v1 1.0.3+c1455e800c via fabric
	- fabric-commands-v0 0.2.1+c1455e800c via fabric
	- fabric-containers-v0 0.1.4+c1455e800c via fabric
	- fabric-content-registries-v0 0.1.4+c1455e800c via fabric
	- fabric-crash-report-info-v1 0.1.3+c1455e800c via fabric
	- fabric-dimensions-v1 0.3.1+c1455e800c via fabric
	- fabric-events-interaction-v0 0.4.1+c1455e800c via fabric
	- fabric-events-lifecycle-v0 0.2.1+c1455e800c via fabric
	- fabric-item-api-v1 1.1.1+c1455e800c via fabric
	- fabric-item-groups-v0 0.2.1+c1455e800c via fabric
	- fabric-key-binding-api-v1 1.0.2+c1455e800c via fabric
	- fabric-keybindings-v0 0.2.1+c1455e800c via fabric
	- fabric-lifecycle-events-v1 1.2.1+c1455e800c via fabric
	- fabric-loot-tables-v1 0.1.6+c1455e800c via fabric
	- fabric-mining-levels-v0 0.1.3+c1455e800c via fabric
	- fabric-models-v0 0.1.1+c1455e800c via fabric
	- fabric-networking-api-v1 1.0.1+c1455e800c via fabric
	- fabric-networking-blockentity-v0 0.2.4+c1455e800c via fabric
	- fabric-networking-v0 0.2.1+c1455e800c via fabric
	- fabric-object-builder-api-v1 1.3.2+c1455e800c via fabric
	- fabric-object-builders-v0 0.6.1+c1455e800c via fabric
	- fabric-particles-v1 0.2.2+c1455e800c via fabric
	- fabric-registry-sync-v0 0.7.2+c1455e800c via fabric
	- fabric-renderer-api-v1 0.2.11+c1455e800c via fabric
	- fabric-renderer-indigo 0.3.5+c1455e800c via fabric
	- fabric-renderer-registries-v1 2.1.1+c1455e800c via fabric
	- fabric-rendering-data-attachment-v1 0.1.4+c1455e800c via fabric
	- fabric-rendering-fluids-v1 0.1.7+c1455e800c via fabric
	- fabric-rendering-v0 1.1.1+c1455e800c via fabric
	- fabric-rendering-v1 1.2.1+c1455e800c via fabric
	- fabric-resource-loader-v0 0.1.11+c1455e800c via fabric
	- fabric-tag-extensions-v0 0.1.4+c1455e800c via fabric
	- fabric-textures-v0 1.0.5+c1455e800c via fabric
	- fabric-tool-attribute-api-v1 1.2.4+c1455e800c via fabric
	- fabricloader 0.12.12
	- java 8
	- mcvmcomputers 1.4.12
	- minecraft 1.15.2
[09:20:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/crazysharky19/.var/app/com.mojang.Minecraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[09:20:59] [main/INFO]: Setting user: NeonCat19
[09:21:01] [main/INFO]: [Indigo] Registering Indigo renderer!
[09:21:01] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[09:21:02] [main/INFO]: Narrator library successfully loaded
[09:21:03] [main/INFO]: Reloading ResourceManager: Default, Fabric API, Fabric API Base, Fabric Biomes (v1), Fabric BlockRenderLayer Registration (v1), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Loader, VM Computers
[09:21:06] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in mcvmcomputers:item/flatscreen
[09:21:06] [main/INFO]: OpenAL initialized.
[09:21:06] [main/INFO]: Sound engine started
[09:21:06] [main/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[09:21:06] [main/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[09:21:06] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:21:06] [main/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:21:06] [main/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:21:06] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:21:06] [main/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:21:07] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[09:21:07] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:21:07] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:21:13] [main/INFO]: [STDERR]: java.io.IOException: Cannot run program "vboxmanage": error=2, No such file or directory
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[09:21:13] [main/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues.confirmButton(SetupPageMaxValues.java:106)
[09:21:13] [main/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues.lambda$init$2(SetupPageMaxValues.java:233)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4185.onPress(class_4185.java:18)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4264.onClick(class_4264.java:15)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_339.mouseClicked(class_339.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:86)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:86)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[09:21:13] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1015)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:619)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:204)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[09:21:13] [main/INFO]: [STDERR]: Caused by: java.io.IOException: error=2, No such file or directory
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[09:21:13] [main/INFO]: [STDERR]: 	... 26 more
[09:21:13] [main/INFO]: [STDERR]: java.io.IOException: Cannot run program "vboxwebsrv": error=2, No such file or directory
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[09:21:13] [main/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues.confirmButton(SetupPageMaxValues.java:113)
[09:21:13] [main/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues.lambda$init$2(SetupPageMaxValues.java:233)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4185.onPress(class_4185.java:18)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4264.onClick(class_4264.java:15)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_339.mouseClicked(class_339.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_4069.mouseClicked(class_4069.java:27)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:86)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:86)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:94)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:150)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
[09:21:13] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:123)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1015)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:619)
[09:21:13] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:204)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:21:13] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[09:21:13] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[09:21:13] [main/INFO]: [STDERR]: Caused by: java.io.IOException: error=2, No such file or directory
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[09:21:13] [main/INFO]: [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[09:21:13] [main/INFO]: [STDERR]: 	... 26 more
[09:21:15] [Thread-8/INFO]: [STDERR]: org.virtualbox_6_1.VBoxException: HTTP transport error: java.net.ConnectException: Connection refused (Connection refused)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at org.virtualbox_6_1.VirtualBoxManager.connect(VirtualBoxManager.java:585)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at mcvmcomputers.client.gui.setup.pages.SetupPageMaxValues$2.run(SetupPageMaxValues.java:142)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[09:21:15] [Thread-8/INFO]: [STDERR]: Caused by: com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: java.net.ConnectException: Connection refused (Connection refused)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:208)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:124)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.proxy.$Proxy59.iWebsessionManagerLogon(Unknown Source)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at org.virtualbox_6_1.VirtualBoxManager.connect(VirtualBoxManager.java:566)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	... 2 more
[09:21:15] [Thread-8/INFO]: [STDERR]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.Socket.connect(Socket.java:589)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at java.net.Socket.connect(Socket.java:538)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
[09:21:15] [Thread-8/INFO]: [STDERR]: 	... 16 more

**Comment by swordlink1** [comment] 2022-04-10 02:14
Where is the drive that VirtualBox is installed in?

**Comment by y2k04** [comment] 2023-03-25 21:45
I have had this happen before personally. I found that the VirtualBox service stopped randomly. I am unsure how to fix this, but if it comes up again in my own testing, I will investigate further.

**Comment by y2k04** [comment] 2023-03-26 03:34
Duplicate of #197

**Closed by y2k04** 2023-03-26 03:34 UTC
Labels: bug, help wanted
