### ISSUE TITLE
Server support. *Suggestion*

### ISSUE THREAD

**Issue by Connorcivi** [Delta2Force/MCVmComputers#155] opened 2021-01-11 02:35 UTC
This mod is great, but this is just a suggestion. The mod should work on a multiplayer server and once it's loaded into the server, the server will launch Virtualbox. If the server doesn't support Virtualbox then the mod will disable it and error saying the system requires Virtualbox and the system you're using isn't supported.

I would love to see this become a feature.

**Comment by swordlink1** [comment] 2021-01-14 23:57
There already is server support.

**Comment by CoccodrillooXDS** [comment] 2021-01-15 10:34
@swordlink1 He/she probably means a server-side Virtual Machine.
(It could be useful for people with low-spec computer)

**Comment by Connorcivi** [comment] 2021-01-15 17:29
Yep, that's what I mean because players don't really have high spec computers but probably have another pc sitting around for friends to use as well. Also, I'm a he if you're wondering.

**Comment by Dogleader6** [comment] 2021-04-20 21:09
wouldn't this also be useful if you want to let another person use your vm in multiplayer? (there'd have to be password locks n stuff) I don't think it's possible to use someone else's vm in multiplayer (at least that's my reasoning since it's stored on a player's machine) this would be cool.

**Comment by y2k04** [comment] 2023-03-26 03:12
Duplicate of #10

**Closed by y2k04** 2023-03-26 03:12 UTC
Labels: enhancement
