### ISSUE TITLE
virtualbox wont start

### ISSUE THREAD

**Issue by asdaeshndj** [Delta2Force/MCVmComputers#278] opened 2023-02-07 07:48 UTC
pretty sure this is the same issue as #260 
currently stuck at attempting to start virtualbox for several hours sitting down and watch the mod attempting to start virtualbox
(yeah i installed everything correctly and restarted minecraft)

**Comment by y2k04** [comment] 2023-03-26 02:43
You are right, duplicate of #260

**Closed by y2k04** 2023-03-26 02:43 UTC
Labels: bug
