### ISSUE TITLE
Doesn't seem to be a cursor

### ISSUE THREAD

**Issue by tburgeson** [Delta2Force/MCVmComputers#224] opened 2021-08-21 04:51 UTC
I tried to load Ubuntu 20.04 and when it launched there was no cursor visible in the VM. I could move my mouse and it would highlight things, but no visible cursor

**Comment by Minelsgo** [comment] 2022-08-21 11:34
same

**Comment by y2k04** [comment] 2023-03-26 03:13
Duplicate of #14

**Closed by y2k04** 2023-03-26 03:13 UTC
Labels: bug
