### ISSUE TITLE
Nothing Showing Up on Display When PC Started With an Iso

### ISSUE THREAD

**Issue by ghost** [Delta2Force/MCVmComputers#262] opened 2022-08-05 15:49 UTC
I am using minecraft 1.16.5. I use Arch Linux, and my client is ATLauncher. I have fabric version 1.16.5 and I have follow the tutorials exactly how they were executed help please?

**Comment by y2k04** [comment] 2023-01-03 23:13
Could you please explain this with more detail and screenshots of VirtualBox and Minecraft running the mod at the same time?

**Comment by y2k04** [comment] 2023-03-26 03:37
Duplicate of #45

**Closed by y2k04** 2023-03-26 03:37 UTC
Labels: bug
