### ISSUE TITLE
VMware could maybe be possible

### ISSUE THREAD

**Issue by privatedev11** [Delta2Force/MCVmComputers#148] opened 2020-12-05 19:17 UTC
# VMware could be possible
VMware has a webpage here saying about their APIs and SDKs. https://www.vmware.com/support/pubs/sdk_pubs.html
It says on one of them about Java.
I'll have a look for some open source stuff about VMware 😄

**Comment by Busaruba2011** [comment] 2020-12-05 19:19
They have a GitHub acc: github.com/vmware

**Comment by BlueJay113** [comment] 2020-12-15 23:30
https://github.com/vmware/open-vm-tools
https://sourceforge.net/projects/open-vm-tools/

This is what you would probably want to look at, seems like something that would be helpful (in the slightest).

**Comment by KirbyTheStar9** [comment] 2020-12-28 21:30
yes

**Comment by lc67846** [comment] 2020-12-31 03:53
Yeah This Just My Opin But I Use VMware For a living and i think virtualbox sucks because you cant do the iso from the start of create

**Comment by Busaruba2011** [comment] 2021-01-01 19:50
> Yeah This Just My Opin But I Use VMware For a living and i think virtualbox sucks because you cant do the iso from the start of create

VirtualBox is ok but vmware is just better i think

**Comment by lc67846** [comment] 2021-01-03 12:12
Same

**Comment by y2k04** [comment] 2022-10-22 02:51
I'll do some reading, yes I know this was abandoned, but it would be good to at least try and revive it?

**Comment by privatedev11** [comment] 2022-10-27 13:33
> I'll do some reading, yes I know this was abandoned, but it would be good to at least try and revive it?

Yeah that sounds good

**Comment by y2k04** [comment] 2023-03-26 03:40
Duplicate of #80

**Closed by y2k04** 2023-03-26 03:40 UTC
Labels: enhancement
