### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by 0WhiteSound** [Delta2Force/MCVmComputers#111] opened 2020-10-04 15:37 UTC
When im turning on pc then nothing is happening (no error message, black screen)

**Comment by Delta2Force** [comment] 2020-10-05 04:50
What’s your OS?

**Comment by 133434543** [comment] 2020-10-05 12:44
Windows 10 Pro

**Comment by 133434543** [comment] 2020-10-05 12:46
> What’s your OS?

Windows 10 Pro

**Comment by y2k04** [comment] 2023-03-26 03:38
Duplicate of #45

**Closed by y2k04** 2023-03-26 03:38 UTC
Labels: bug
