### ISSUE TITLE
translation in Chinese Simplified

### ISSUE THREAD

**Issue by kaoyu555666777** [Delta2Force/MCVmComputers#271] opened 2023-01-05 02:59 UTC
![image.png](https://s2.loli.net/2023/01/05/xYBdqRjMie5syn2.png)
No translation in Chinese Simplified(zh_cn.json),but I saw Chinese Traditional(zh_tw.json)
So I took zh_tw. Json into simplified Chinese
[zh_cn.zip](https://github.com/Delta2Force/MCVmComputers/files/10348971/zh_cn.zip)

**Comment by y2k04** [comment] 2023-03-26 03:18
Duplicate of #223

**Closed by y2k04** 2023-03-26 03:18 UTC
Labels: enhancement, help wanted
